name: Update Top 10 Languages

on:
  schedule:
    - cron: '0 2 * * 1' # Setiap Senin pagi
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-top-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Jalankan script update top languages
        run: python scripts/update_top_languages.py
      - name: Commit and push jika berubah
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update top 10 languages [skip ci]" || exit 0
          git push
